// Code generated by protoc-gen-go. DO NOT EDIT.
// source: store/store.proto

/*
Package store is a generated protocol buffer package.

It is generated from these files:
	store/store.proto

It has these top-level messages:
	StoreEvent
	MsgCreated
	MsgUpdated
	MsgDeleted
*/
package store

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StoreEvent_Type int32

const (
	StoreEvent_Unknown    StoreEvent_Type = 0
	StoreEvent_MsgCreated StoreEvent_Type = 32
	StoreEvent_MsgUpdated StoreEvent_Type = 33
	StoreEvent_MsgDeleted StoreEvent_Type = 34
)

var StoreEvent_Type_name = map[int32]string{
	0:  "Unknown",
	32: "MsgCreated",
	33: "MsgUpdated",
	34: "MsgDeleted",
}
var StoreEvent_Type_value = map[string]int32{
	"Unknown":    0,
	"MsgCreated": 32,
	"MsgUpdated": 33,
	"MsgDeleted": 34,
}

func (x StoreEvent_Type) String() string {
	return proto.EnumName(StoreEvent_Type_name, int32(x))
}
func (StoreEvent_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

// An event
type StoreEvent struct {
	Type       StoreEvent_Type `protobuf:"varint,1,opt,name=type,enum=StoreEvent_Type" json:"type,omitempty"`
	TsNanos    uint64          `protobuf:"varint,2,opt,name=tsNanos" json:"tsNanos,omitempty"`
	MsgCreated *MsgCreated     `protobuf:"bytes,32,opt,name=msgCreated" json:"msgCreated,omitempty"`
	MsgUpdated *MsgUpdated     `protobuf:"bytes,33,opt,name=msgUpdated" json:"msgUpdated,omitempty"`
	MsgDeleted *MsgDeleted     `protobuf:"bytes,34,opt,name=msgDeleted" json:"msgDeleted,omitempty"`
}

func (m *StoreEvent) Reset()                    { *m = StoreEvent{} }
func (m *StoreEvent) String() string            { return proto.CompactTextString(m) }
func (*StoreEvent) ProtoMessage()               {}
func (*StoreEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *StoreEvent) GetType() StoreEvent_Type {
	if m != nil {
		return m.Type
	}
	return StoreEvent_Unknown
}

func (m *StoreEvent) GetTsNanos() uint64 {
	if m != nil {
		return m.TsNanos
	}
	return 0
}

func (m *StoreEvent) GetMsgCreated() *MsgCreated {
	if m != nil {
		return m.MsgCreated
	}
	return nil
}

func (m *StoreEvent) GetMsgUpdated() *MsgUpdated {
	if m != nil {
		return m.MsgUpdated
	}
	return nil
}

func (m *StoreEvent) GetMsgDeleted() *MsgDeleted {
	if m != nil {
		return m.MsgDeleted
	}
	return nil
}

// A new message has been created, should include all the data
// required by query so it doesn't need to pull data from ES. Besides,
// by the time it reaches query, data in ES might have changed.
type MsgCreated struct {
	Index string `protobuf:"bytes,1,opt,name=index" json:"index,omitempty"`
	Id    string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Type  string `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	Ver   int64  `protobuf:"varint,4,opt,name=ver" json:"ver,omitempty"`
}

func (m *MsgCreated) Reset()                    { *m = MsgCreated{} }
func (m *MsgCreated) String() string            { return proto.CompactTextString(m) }
func (*MsgCreated) ProtoMessage()               {}
func (*MsgCreated) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MsgCreated) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *MsgCreated) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MsgCreated) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *MsgCreated) GetVer() int64 {
	if m != nil {
		return m.Ver
	}
	return 0
}

// An existing message has been updated
type MsgUpdated struct {
}

func (m *MsgUpdated) Reset()                    { *m = MsgUpdated{} }
func (m *MsgUpdated) String() string            { return proto.CompactTextString(m) }
func (*MsgUpdated) ProtoMessage()               {}
func (*MsgUpdated) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

// An existing message has been deleted
type MsgDeleted struct {
}

func (m *MsgDeleted) Reset()                    { *m = MsgDeleted{} }
func (m *MsgDeleted) String() string            { return proto.CompactTextString(m) }
func (*MsgDeleted) ProtoMessage()               {}
func (*MsgDeleted) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*StoreEvent)(nil), "StoreEvent")
	proto.RegisterType((*MsgCreated)(nil), "MsgCreated")
	proto.RegisterType((*MsgUpdated)(nil), "MsgUpdated")
	proto.RegisterType((*MsgDeleted)(nil), "MsgDeleted")
	proto.RegisterEnum("StoreEvent_Type", StoreEvent_Type_name, StoreEvent_Type_value)
}

func init() { proto.RegisterFile("store/store.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0x41, 0x4b, 0xfc, 0x30,
	0x10, 0xc5, 0xff, 0x69, 0xbb, 0xff, 0xb2, 0x53, 0x29, 0x31, 0x78, 0xc8, 0x31, 0x1b, 0x3c, 0x14,
	0x84, 0x0a, 0xeb, 0x37, 0x70, 0xf5, 0xa8, 0x87, 0xe8, 0x82, 0x78, 0x5b, 0xc9, 0x20, 0x45, 0x4d,
	0x4a, 0x1b, 0x56, 0xf7, 0x9b, 0xf8, 0x71, 0xa5, 0xd9, 0xd1, 0xe6, 0x52, 0xfa, 0xde, 0xfb, 0x91,
	0x19, 0xde, 0xc0, 0xe9, 0x18, 0xfc, 0x80, 0x97, 0xf1, 0xdb, 0xf6, 0x83, 0x0f, 0x5e, 0x7f, 0x67,
	0x00, 0x0f, 0x93, 0xbe, 0xdd, 0xa3, 0x0b, 0xe2, 0x1c, 0x8a, 0x70, 0xe8, 0x51, 0x32, 0xc5, 0x9a,
	0x7a, 0xcd, 0xdb, 0x39, 0x6a, 0x1f, 0x0f, 0x3d, 0x9a, 0x98, 0x0a, 0x09, 0x65, 0x18, 0xef, 0x77,
	0xce, 0x8f, 0x32, 0x53, 0xac, 0x29, 0xcc, 0xaf, 0x14, 0x17, 0x00, 0x1f, 0xe3, 0xeb, 0x66, 0xc0,
	0x5d, 0x40, 0x2b, 0x95, 0x62, 0x4d, 0xb5, 0xae, 0xda, 0xbb, 0x3f, 0xcb, 0x24, 0x31, 0xc1, 0xdb,
	0xde, 0x46, 0x78, 0x35, 0xc3, 0x64, 0x99, 0x24, 0x26, 0xf8, 0x06, 0xdf, 0x71, 0x82, 0xf5, 0x0c,
	0x93, 0x65, 0x92, 0x58, 0x6f, 0xa0, 0x98, 0xd6, 0x15, 0x15, 0x94, 0x5b, 0xf7, 0xe6, 0xfc, 0xa7,
	0xe3, 0xff, 0x44, 0x0d, 0x30, 0x2f, 0xc2, 0x15, 0x69, 0x7a, 0x9f, 0xaf, 0x48, 0xd3, 0x13, 0x5c,
	0xeb, 0xa7, 0x94, 0x17, 0x67, 0xb0, 0xe8, 0x9c, 0xc5, 0xaf, 0x58, 0xcd, 0xd2, 0x1c, 0x85, 0xa8,
	0x21, 0xeb, 0x6c, 0x2c, 0x61, 0x69, 0xb2, 0xce, 0x0a, 0x41, 0xfd, 0xe5, 0xd1, 0x39, 0xb6, 0xc5,
	0x21, 0xdf, 0xe3, 0x20, 0x0b, 0xc5, 0x9a, 0xdc, 0x4c, 0xbf, 0xfa, 0x24, 0x9d, 0x4c, 0x8a, 0xe6,
	0x5e, 0x97, 0xcf, 0x8b, 0x78, 0x9f, 0x97, 0xff, 0xf1, 0x40, 0x57, 0x3f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xff, 0x75, 0x3a, 0x33, 0xb5, 0x01, 0x00, 0x00,
}
