// Code generated by "stringer -type=PipelineStat"; DO NOT EDIT.

package core

import "fmt"

const _PipelineStat_name = "PipelineUnintPipelineInitedPipelineStartedPipelineStopped"

var _PipelineStat_index = [...]uint8{0, 13, 27, 42, 57}

func (i PipelineStat) String() string {
	if i >= PipelineStat(len(_PipelineStat_index)-1) {
		return fmt.Sprintf("PipelineStat(%d)", i)
	}
	return _PipelineStat_name[_PipelineStat_index[i]:_PipelineStat_index[i+1]]
}
